# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared/phaethon.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15shared/phaethon.proto\"q\n\x08\x41\x44SBData\x12\x0b\n\x03hex\x18\x01 \x01(\t\x12\x0e\n\x06\x66light\x18\x02 \x01(\t\x12\x0b\n\x03lat\x18\x03 \x01(\x02\x12\x0b\n\x03lon\x18\x04 \x01(\x02\x12\x10\n\x08\x61ltitude\x18\x05 \x01(\r\x12\r\n\x05track\x18\x06 \x01(\r\x12\r\n\x05speed\x18\x07 \x01(\r\"\x19\n\x0b\x41\x63knowledge\x12\n\n\x02ok\x18\x01 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shared.phaethon_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ADSBDATA']._serialized_start=25
  _globals['_ADSBDATA']._serialized_end=138
  _globals['_ACKNOWLEDGE']._serialized_start=140
  _globals['_ACKNOWLEDGE']._serialized_end=165
# @@protoc_insertion_point(module_scope)
